# Generated by Django 6.0.3 on 2026-03-15 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='班级')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('enrollment_year', models.IntegerField(blank=True, null=True, verbose_name='入学年份')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='StudentExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('answers', models.JSONField(default=dict, verbose_name='答案')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否完成')),
                ('time_spent', models.IntegerField(default=0, verbose_name='用时(秒)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'db_table': 'student_exam_record',
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
