# Generated by Django 6.0.3 on 2026-03-15 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentexamrecord',
            index=models.Index(fields=['student', 'is_finished'], name='student_exa_student_520a33_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamrecord',
            index=models.Index(fields=['submit_time'], name='student_exa_submit__cc8195_idx'),
        ),
    ]
