# Generated by Django 6.0.3 on 2026-03-23 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentexamrecord_student_exa_student_520a33_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='批改时间'),
        ),
        migrations.AddField(
            model_name='studentexamrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentexamrecord',
            name='teacher_comments',
            field=models.TextField(blank=True, null=True, verbose_name='教师评语'),
        ),
    ]
