# Generated by Django 6.0.3 on 2026-05-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_add_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='deleted_wrong_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='已删除错题ID'),
        ),
    ]
