# Generated by Django 6.0.3 on 2026-05-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_deleted_wrong_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamrecord',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
