# Generated by Django 6.0.3 on 2026-03-23 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['order'], 'verbose_name': '考试题目', 'verbose_name_plural': '考试题目'},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_by'], name='exam_created_a4647c_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time', 'end_time'], name='exam_start_t_11b62b_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published'], name='exam_is_publ_11fa22_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam'], name='exam_questi_exam_id_37de61_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['question_id'], name='exam_questi_questio_201455_idx'),
        ),
    ]
