# Generated by Django 6.0.3 on 2026-04-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='enable_monitoring',
            field=models.BooleanField(default=False, verbose_name='启用监控'),
        ),
        migrations.AddField(
            model_name='exam',
            name='random_options',
            field=models.BooleanField(default=False, verbose_name='随机选项顺序'),
        ),
        migrations.AddField(
            model_name='exam',
            name='random_questions',
            field=models.BooleanField(default=False, verbose_name='随机题目顺序'),
        ),
    ]
