# Generated by Django 6.0.3 on 2026-03-15 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('essay', '简答题')], max_length=20, verbose_name='题型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(default=dict, help_text='单选题/多选题的选项，格式：{"A": "选项A", "B": "选项B"}', verbose_name='选项')),
                ('answer', models.TextField(help_text='单选题存"A"，多选题存"A,B,C"，判断题存"对"或"错"', verbose_name='正确答案')),
                ('analysis', models.TextField(blank=True, verbose_name='答案解析')),
                ('score', models.IntegerField(default=5, verbose_name='默认分值')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '较易'), (3, '中等'), (4, '较难'), (5, '困难')], default=3, verbose_name='难度')),
                ('chapter', models.CharField(blank=True, max_length=100, verbose_name='所属章节')),
                ('knowledge_point', models.CharField(blank=True, max_length=200, verbose_name='知识点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题',
                'db_table': 'question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('department', models.CharField(max_length=100, verbose_name='院系')),
                ('title', models.CharField(blank=True, choices=[('assistant', '助教'), ('lecturer', '讲师'), ('associate', '副教授'), ('professor', '教授')], max_length=50, verbose_name='职称')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('office', models.CharField(blank=True, max_length=100, verbose_name='办公室')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'teacher_profile',
            },
        ),
    ]
