# Generated by Django 6.0.3 on 2026-04-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_question_question_created_bd3705_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='标签描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目标签',
                'verbose_name_plural': '题目标签',
                'db_table': 'question_tag',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('essay', '简答题'), ('fill', '填空题'), ('discussion', '论述题')], max_length=20, verbose_name='题型'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='teachers.questiontag', verbose_name='标签'),
        ),
    ]
