# Generated by Django 6.0.3 on 2026-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_questiontag_alter_question_type_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
    ]
